dist: xenial
sudo: required

os:
  - linux

jdk:
  - openjdk8

language: go

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel

script:
  - bazel version
  - bazel build //docs/...
  - cd examples && ./ci.sh
